server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    name: recipesdb
    url: jdbc:postgresql://localhost:5432/recipesdb
    username: postgres
    password: postgres
  jpa:
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
    show-sql: false
debug: true 